### ISSUE TITLE
Wifi R10 Support

### ISSUE THREAD

**Issue by JWynegar** [bropat/eufy-security-ws#149]
### Describe the solution you'd like

Can we get support for the R10 Retrofit lock?

**Comment by bropat** [comment]
You can, but you have to open a feature request in the eufy-security-client project.
So that I can then support the device, I must have access to it. 

Note: If you don't want to share the device with me, please don't open the feature request at all. Since I can't do anything anyway.

Thanks for your understanding!

After it is supported there, it will simply be supported here automatically with the next update of the driver (eufy-security-client).
