### ISSUE TITLE
[Feature request]: Initialization flow

### ISSUE THREAD

**Issue by fuatakgun** [bropat/eufy-security-ws#211]
### Describe the solution you'd like

Cont. from https://github.com/bropat/eufy-security-ws/issues/150

I am having issues to receive `captcha/verification (2fa)` events from WS on container, assuming that before I can even reach to `start listening` state, WS on container had already tried logging in and received respective events.

So timeline perspective;
- t0: launch the docker container with login credentials
- t1: receive captcha or verification (2fa) but it would not be delivered any client as there is none yet
- t2: client connects and activate `start listening`
- t3: client does not know about current state regarding to `captcha` or `verify (2fa)` so it cannot react accordingly.

Suggestions;
- we can wait for the first client to initiate login flow, this might be an extreme change given the impact on all other consumers (not sure how many)
- we can create a new command to initiate login flow.

**Comment by bropat** [comment]
As soon as `eufy-security-ws` receives a captcha request, it is cached so that every client that connects and executes `start listening` also receives the event as long as no client has sent the captcha. Look [here](https://github.com/bropat/eufy-security-ws/blob/0cef884d71a4fad9e61638d314fbfb5aa72d93e1/src/lib/server.ts#L108-L117) and [here](https://github.com/bropat/eufy-security-ws/blob/0cef884d71a4fad9e61638d314fbfb5aa72d93e1/src/lib/driver/message_handler.ts#L36-L58).
What has not been implemented is whether a captcha has expired in the meantime (this information is not available and could only be implemented with a simple timer), but if the captcha request is answered incorrectly, you get another one right away ;)

> we can create a new command to initiate login flow.

There is already a command to initiate a connection. See [here](https://bropat.github.io/eufy-security-ws/#/api_cmds?id=connect-to-cloud-and-push-notifications).

**Comment by fuatakgun** [comment]
my findings;
- when captcha event is received, before forwarding the event to the client, it is trying to dump the state (https://github.com/bropat/eufy-security-ws/blob/0cef884d71a4fad9e61638d314fbfb5aa72d93e1/src/lib/server.ts#LL99C31-L99C31) 
- but it waits for event `stations loaded` (https://github.com/bropat/eufy-security-client/blob/76772a2f49aae2b05f4c17eab5294831b2886c65/src/eufysecurity.ts#L291)
- this event will probably not arrive as it is stuck with captcha request

**Comment by fuatakgun** [comment]
when I am running client against server, this is the response;
```
ts-node src/bin/client.ts 
{
  type: 'version',
  driverVersion: '2.5.1',
  serverVersion: '1.4.1',
  minSchemaVersion: 0,
  maxSchemaVersion: 17
}
{
  type: 'result',
  success: true,
  messageId: 'api-schema-id',
  result: {}
}
```

**Comment by bropat** [comment]
@fuatakgun checkout latest version (`1.6.0`).
