### ISSUE TITLE
[Bug]: Command aged out after few days

### ISSUE THREAD

**Issue by SimonCtl** [bropat/eufy-security-ws#328]
### Version

1.8.0-2

### Node version

N/A

### Operating System type

Linux

### Operating system version

HA 2024.5.3

### Describe the bug

Hi,

I have a eufy S100 camera and every 2 or 3 days. I can no longer control it through HA.
When I check in add-on logs, I see it cannot connect through eufy-security-client.
I have to restart add-on and then it works again. Looks like it's a token issue ?

Thanks for your help !

### To reproduce

.

### Screenshots & Logfiles

![image](https://github.com/bropat/eufy-security-ws/assets/74704575/0e08c5d1-084c-4acb-b771-2f1d94d408a5)

**Comment by domi8671** [comment]
I have the same issue. I am using 10 S100. After restarting the add-on all are working, the next day 2 are not working, restarting the add-on, all are working, the next day 9 are not working... and so on.

I have activated debug mode and it says error connection timeout. Today I took the following screenshot:
![Screenshot](https://github.com/bropat/eufy-security-ws/assets/161075219/6300b661-e3b0-4f6d-acd3-6c364db02f0d)

**Comment by SimonCtl** [comment]
@bropat Hi,
What would you need more to debug ?
I don't have anymore logs related to eufy-security-ws extension.

**Comment by Sticky12** [comment]
I also have this bug.
My logs also state Command aged out.
This only started happening a few days ago for me.

**Comment by bropat** [comment]
This problem is related to connection problems with the device (very well visible [here](https://github.com/bropat/eufy-security-ws/issues/328#issuecomment-2150627587)).
As soon as a P2P command is sent and there is currently no P2P connection with the device, an attempt is made to establish it and if this is not established within a certain time, the command is cancelled (aged out).

In short, normal behaviour in this case.

**Comment by domi8671** [comment]
But how can it be that it works via the Eufy app at the same time? The device can also be reached via the Alexa app at the same time. Just not via Home Assistant.

**Comment by PhilippEngler** [comment]
> But how can it be that it works via the Eufy app at the same time? The device can also be reached via the Alexa app at the same time. Just not via Home Assistant.

Maybe your Home Assistant could not built up a p2p connection to the device due to network card / operating system problems or whatever.

In normal case, your log should have entries like `Connected to station T80X on host XXX.XXX.XXX.XXX and port XXXXX`. In the case of failing p2p connections, there should be log entries like `Tried all hosts, no connection could be established to station T80X.` and `Timeout connecting to station T80X.`.
