### ISSUE TITLE
Request: can we include `is_livestreaming` and `is_rtsp_livestreaming` into device state

### ISSUE THREAD

**Issue by fuatakgun** [bropat/eufy-security-ws#33]
What is the additional cost and complexity of including these as attributes of device state?
Moreover, we can fire events as `property_changed` for `is_livestreaming` and `is_rtsp_livestreaming` True and False.

Now, i need to send start rtsp livestream command and check its result. I am not getting any event.
For p2p livestream, it generates `livestream started` and `livestream_stopped` but it could be managed via specific attributes mentioned above.

**Comment by bropat** [comment]
@fuatakgun 

These attributes cannot be handled as device attributes because streaming is not handled by the device class but by the station class.
The attributes are modelled on the effective attributes of the manufacturer implementation. Starting the live stream is a command, not an attribute in the manufacturer implementation.
Introducing the attributes in the station would be possible but from my point of view unclean.

> Now, i need to send start rtsp livestream command and check its result. I am not getting any event.

Furthermore, what you write here is not correct, because there are also the respective events for handling the RTSP stream (you have opened a separate issue for this: #40). There is currently still a bug with the stop event, which will be fixed in eufy-security-client 1.2.2.

For the reasons stated above, I will not pursue this demand.

**Comment by fuatakgun** [comment]
you are right in terms of internal mechanisms of handling livestream and rtsp livestream, but data modelling perspective, they look like attributes of respective devices.
