### ISSUE TITLE
[Bug]: Error status return not 200

### ISSUE THREAD

**Issue by ronaldt80** [bropat/eufy-security-ws#73]
### Version

0.7

### Node version

?

### Operating System type

Docker

### Operating system version

HASS OS

### Describe the bug

Repeated status 204, it seems add-on expects 200; any thoughts what this relates to?

In addition I have repeated comments around push notification closing and P2P client protocol:
```
P2PClientProtocol.lookup(): station: T800Nxxx - All address lookup tentatives failed. 
2022-01-23 12:48:21.184  INFO  Timeout connecting to station T8010xxx

2022-01-23 19:26:47.040  INFO  Push notification connection closed 
2022-01-23 19:26:47.241  ERROR Status return code not 200 
{
  status: 204,
  statusText: 'No Content'
}
```

### To reproduce

1. Run Eufy security 0.7.0
2. Run home assistant integration v. 2.3.0
3. See error

### Additional context

I tried rebooting the homebase as initially I suspected there was a relationship with recently changed vlan settings. Ruled out, homebase works, as does Eufy app. Homebase is now on same lan as the docker machine, no firewalls in place

**Comment by tomvmeer** [comment]
Had the same issue, I think it's the container remembering old settings that are no longer valid on your current network.
I removed the Docker container and rebuild, this fixed the issue.

**Comment by ronaldt80** [comment]
That's interesting, can't try it out anymore - my errors disappeared 3 days ago after a full reboot of the host system following an upgrade of homeassistant to 7.2; probably this had the same effect - a reset of parameters. I was expecting the errors to return but after 3 days and with your explanation above I think we can close the issue. Unless others are still struggling?

**Comment by skank01** [comment]
For me this is still present, i dont have to build container, i just use the addon from fuatakgun

**Comment by ronaldt80** [comment]
Remove it in full and reinstall it, should be the same effect. The add on is a docker container

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by handsome1987** [comment]
I also have still the same 404 error before the stream start

**Comment by skank01** [comment]
Tried reinstalling now i get this :
2022-01-27 19:19:46.916  ERROR Create push credentials Error: 
 Error  FID registration failed with error: Error: FID registration failed with error: undefined
error stack:
• service.ts:91 registerFid
    node_modules/eufy-security-client/src/push/service.ts:91:19
• task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
• service.ts:144 createPushCredentials
    node_modules/eufy-security-client/src/push/service.ts:144:16
• service.ts:506 _open
    node_modules/eufy-security-client/src/push/service.ts:506:32
• service.ts:565 open
    node_modules/eufy-security-client/src/push/service.ts:565:9
• service.ts:576 <anonymous>
    node_modules/eufy-security-client/src/push/service.ts:576:17
2022-01-27 19:19:46.921  INFO  Push notification connection closed 
2022-01-27 19:19:46.923  ERROR Push notifications are disabled, because the registration failed! 
2022-01-27 19:19:46.925  INFO  Retry to register/login for push notification in 300 seconds... 
2022-01-27 19:24:47.023  INFO  Retry to register/login for push notification 
2022-01-27 19:24:54.245  ERROR registerFid - Error: 
 RequestError  connect ECONNREFUSED 0.0.0.0:443
details:
{
  code: 'ECONNREFUSED',
  timings: undefined
}
error stack:
• index.js:1183 _makeRequest
    node_modules/got/dist/source/core/index.js:1183:19
• task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
• index.js:334 <anonymous>
    node_modules/got/dist/source/core/index.js:334:17
2022-01-27 19:24:54.250  ERROR registerFid - Status return code not 200 
{
  status: undefined,
  statusText: undefined,
  data: undefined
}
